export const designSystemBlueprint = {
  direction: "premium glassmorphic SaaS",
  palette: {
    background: "#07080F",
    surface: "rgba(255,255,255,0.04)",
    surfaceAlt: "rgba(255,255,255,0.07)",
    border: "rgba(255,255,255,0.10)",
    text: "#F3F6FF",
    muted: "#A3ACC4",
    primary: "#5B6EF5",
    secondary: "#2ECFB5",
    accent: "#8B5CF6",
    success: "#34D399",
    warning: "#FBBF24",
    danger: "#FB7185",
  },
  layout: {
    homepage: ["nav", "hero", "trust-bar", "feature-grid", "workspace-preview", "cta"],
    workspace: ["left-sidebar", "top-bar", "main-canvas", "right-collaboration-rail"],
    mobile: ["stacked-panels", "collapsible-sidebar", "scrollable-tabs"],
  },
  components: [
    "GlassCard",
    "PrimaryButton",
    "SecondaryButton",
    "GhostButton",
    "Pill",
    "StatusChip",
    "PermissionTag",
    "Tabs",
    "Dropdown",
    "Modal",
    "Sidebar",
    "TopBar",
    "RightRail",
    "MetricTile",
    "ActivityItem",
    "ChatBubble",
    "ThreadPanel",
    "FileCard",
    "DocBlock",
    "CommentBlock",
  ],
  motion: {
    hover: "subtle background shift, tiny lift, gentle border glow",
    focus: "clear ring, no heavy glow",
    loading: "polished skeletons and calm transitions",
  },
  responsive: {
    desktop: "multi-column, strong hierarchy",
    tablet: "compressed sidebar, tighter spacing",
    mobile: "stacked panels, icon-first tabs, horizontal overflow only where necessary",
  },
  implementation: {
    stack: "Next.js + Tailwind",
    approach: "token-based utilities, composable variants, reusable primitives, shared glass surface rules",
  },
} as const;
